# Generated by Django 5.0.6 on 2024-05-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_reg_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_reg_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
